from nstil.services.ai.prompt_bank.types import CuratedPrompt, PromptIntensity, PromptTag

ALL = frozenset({"happy", "calm", "sad", "anxious", "angry", "neutral"})
POSITIVE = frozenset({"happy", "calm", "neutral"})
DIFFICULT = frozenset({"sad", "anxious", "angry"})

CHECK_IN_PROMPTS: tuple[CuratedPrompt, ...] = (
    CuratedPrompt(
        id="ci-001",
        prompt_type="check_in",
        content="How are you feeling right now? Take a moment to notice what's present.",
        mood_categories=ALL,
        tags=frozenset({PromptTag.EMOTIONS, PromptTag.MINDFULNESS}),
        intensity=PromptIntensity.LIGHT,
    ),
    CuratedPrompt(
        id="ci-002",
        prompt_type="check_in",
        content="What's one word that describes your day so far?",
        mood_categories=ALL,
        tags=frozenset({PromptTag.EMOTIONS, PromptTag.REFLECTION}),
        intensity=PromptIntensity.LIGHT,
    ),
    CuratedPrompt(
        id="ci-003",
        prompt_type="check_in",
        content="What's been on your mind today?",
        mood_categories=ALL,
        tags=frozenset({PromptTag.REFLECTION}),
        intensity=PromptIntensity.LIGHT,
    ),
    CuratedPrompt(
        id="ci-004",
        prompt_type="check_in",
        content="What's something that made you smile recently?",
        mood_categories=POSITIVE,
        tags=frozenset({PromptTag.JOY, PromptTag.GRATITUDE}),
        intensity=PromptIntensity.LIGHT,
    ),
    CuratedPrompt(
        id="ci-005",
        prompt_type="check_in",
        content="What's giving you energy today?",
        mood_categories=POSITIVE,
        tags=frozenset({PromptTag.ENERGY, PromptTag.JOY}),
        intensity=PromptIntensity.LIGHT,
    ),
    CuratedPrompt(
        id="ci-006",
        prompt_type="check_in",
        content="What's one thing you're looking forward to?",
        mood_categories=POSITIVE,
        tags=frozenset({PromptTag.FUTURE, PromptTag.JOY}),
        intensity=PromptIntensity.LIGHT,
    ),
    CuratedPrompt(
        id="ci-007",
        prompt_type="check_in",
        content="It sounds like things have been tough. What's weighing on you?",
        mood_categories=DIFFICULT,
        tags=frozenset({PromptTag.EMOTIONS, PromptTag.RESILIENCE}),
        intensity=PromptIntensity.MODERATE,
    ),
    CuratedPrompt(
        id="ci-008",
        prompt_type="check_in",
        content="What would feel like a small win for you today?",
        mood_categories=DIFFICULT,
        tags=frozenset({PromptTag.GOALS, PromptTag.RESILIENCE}),
        intensity=PromptIntensity.LIGHT,
    ),
    CuratedPrompt(
        id="ci-009",
        prompt_type="check_in",
        content="What do you need most right now?",
        mood_categories=DIFFICULT,
        tags=frozenset({PromptTag.SELF_CARE, PromptTag.EMOTIONS}),
        intensity=PromptIntensity.MODERATE,
    ),
    CuratedPrompt(
        id="ci-010",
        prompt_type="check_in",
        content="Is there something you've been avoiding thinking about?",
        mood_categories=ALL,
        tags=frozenset({PromptTag.EMOTIONS, PromptTag.REFLECTION}),
        intensity=PromptIntensity.DEEP,
    ),
    CuratedPrompt(
        id="ci-011",
        prompt_type="check_in",
        content="What's one thing you did today that you're proud of?",
        mood_categories=ALL,
        tags=frozenset({PromptTag.GRATITUDE, PromptTag.GROWTH}),
        intensity=PromptIntensity.LIGHT,
    ),
    CuratedPrompt(
        id="ci-012",
        prompt_type="check_in",
        content="How has your body been feeling today?",
        mood_categories=ALL,
        tags=frozenset({PromptTag.HEALTH, PromptTag.MINDFULNESS}),
        intensity=PromptIntensity.LIGHT,
    ),
    CuratedPrompt(
        id="ci-013",
        prompt_type="check_in",
        content="What's something kind you did for yourself today?",
        mood_categories=ALL,
        tags=frozenset({PromptTag.SELF_CARE}),
        intensity=PromptIntensity.LIGHT,
    ),
    CuratedPrompt(
        id="ci-014",
        prompt_type="check_in",
        content="If you could change one thing about today, what would it be?",
        mood_categories=DIFFICULT,
        tags=frozenset({PromptTag.REFLECTION, PromptTag.CHANGE}),
        intensity=PromptIntensity.MODERATE,
    ),
    CuratedPrompt(
        id="ci-015",
        prompt_type="check_in",
        content="What's a moment from today you want to remember?",
        mood_categories=POSITIVE,
        tags=frozenset({PromptTag.GRATITUDE, PromptTag.MINDFULNESS}),
        intensity=PromptIntensity.LIGHT,
    ),
)
